name: Release
on:
  push:
    branches: [ main, "*.x" ]
jobs:
  release:
    name: Release CDKTF Libraries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: npm install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMREL_GH_TOKEN }}
        run: npx multi-semantic-release